"""Mobile interactions and image configuration, using isolated fake-data HTTP."""
import io
import json
from pathlib import Path
import time

from PIL import Image
from playwright.sync_api import sync_playwright, expect

root = Path(__file__).parent
auth = json.loads((root/'preview_auth.json').read_text())['ledger1']
output = root.parent/'output/playwright'
with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    context = browser.new_context(viewport=dict(width=390, height=844))
    stub = 'window.Telegram={WebApp:{initData:'+json.dumps(auth)+',ready(){},expand(){},enableClosingConfirmation(){window.closing=true},disableClosingConfirmation(){window.closing=false},BackButton:{onClick(fn){window.telegramBack=fn},show(){},hide(){}}}}'
    context.route('https://telegram.org/js/telegram-web-app.js', lambda r: r.fulfill(content_type='text/javascript', body=stub))
    def api(action, payload=None):
        r = context.request.post('http://127.0.0.1:8765/api/miniapp/ledger1/'+action, data=dict(init_data=auth, payload=payload or {}))
        assert r.ok, action
        return r.json()['data']
    for uid in range(700, 712):
        api('staff', dict(user_id=uid, add=True, name='滚动测试'+str(uid), grants=dict(manage=True,global_ops=True,broadcast=True,groups=[-10011])))
    overview = api('overview')
    basics=overview['customer']['basics']
    basics.update(welcome_text='{name} 已加入该群。',welcome_enabled=True)
    api('customer',dict(section='basics',value=basics,revision=overview['customer']['revision']))
    for section in ('ads','replies'):
        overview=api('overview')
        api('customer',dict(section=section,value=[],revision=overview['customer']['revision']))
    overview=api('overview')
    api('welcomephoto',dict(mode='remove',revision=overview['customer']['revision']))
    page = context.new_page()
    errors = []
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.goto('http://127.0.0.1:8765/miniapp/ledger1')
    expect(page.locator('#remaining')).to_be_visible()
    def click(name): page.get_by_role('button',name=name,exact=True).click()
    def back(): page.locator('#back').click()
    def confirm(yes):
        page.locator('#confirmAccept' if yes else '#confirmCancel').click()
    def saved():
        page.wait_for_function('!busy')
        expect(page.locator('#toast')).to_have_text('配置已保存')
    click('用户')
    owner = page.locator('[data-user="111"]')
    expect(owner.locator('.tag')).to_have_text(['admin','全局','单群','广播'])
    assert '›' not in owner.inner_text()
    for width in (320,390):
        page.set_viewport_size(dict(width=width,height=844))
        assert page.locator('.person-row .tag').evaluate_all('els=>els.every(e=>e.getBoundingClientRect().height<30 && getComputedStyle(e).whiteSpace==="nowrap")')
        assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
    page.locator('#search').fill('222')
    page.locator('#search').press('Enter')
    page.locator('[data-user="222"] .tag').click()
    expect(page.locator('#title')).to_have_text('用户配置')
    page.get_by_label('个人汇率',exact=True).fill('5')
    back()
    expect(page.locator('#confirmation')).to_be_visible()
    confirm(False)
    expect(page.get_by_label('个人汇率',exact=True)).to_have_value('5')
    assert page.evaluate('dirty && closing')
    click('编辑人员授权')
    page.evaluate('void telegramBack()')
    expect(page.locator('#editor')).not_to_be_visible()
    assert page.evaluate('dirty && closing')
    click('编辑人员授权')
    page.get_by_label('广播',exact=True).check()
    page.evaluate('void telegramBack()')
    expect(page.locator('#confirmation')).to_be_visible()
    confirm(False)
    expect(page.locator('#editor')).to_be_visible()
    page.evaluate('void telegramBack()')
    confirm(True)
    expect(page.locator('#editor')).not_to_be_visible()
    expect(page.get_by_label('个人汇率',exact=True)).to_have_value('5')
    back();confirm(True)
    expect(page.locator('#title')).to_have_text('用户')
    expect(page.locator('#search')).to_have_value('222')
    page.locator('#search').fill('')
    page.locator('[data-user="710"]').click()
    previous = page.evaluate('trail.at(-1).scroll')
    back()
    page.wait_for_timeout(100)
    assert abs(page.evaluate('scrollY')-previous)<2
    page.locator('[data-user="111"]').click()
    page.get_by_label('个人汇率',exact=True).fill('12')
    pricing_calls = []
    def pricing(route):
        pricing_calls.append(1)
        time.sleep(.2)
        route.continue_()
    page.route('**/api/miniapp/ledger1/pricing',pricing)
    page.get_by_role('button',name='保存个人配置',exact=True).evaluate('(b)=>{b.click();b.click()}')
    saved()
    assert len(pricing_calls)==1
    assert not page.evaluate('dirty || closing')
    click('概览');page.locator('.row[data-go=basics]').click()
    page.get_by_label('进群欢迎语',exact=True).fill('未保存文案{name}')
    click('管理欢迎图片')
    image=io.BytesIO();Image.new('RGB',(24,16),'blue').save(image,format='PNG')
    page.locator('#welcome_file').set_input_files(dict(name='welcome.png',mimeType='image/png',buffer=image.getvalue()))
    expect(page.locator('#welcomePhotoPreview')).to_be_visible()
    expect(page.get_by_role('button',name='保存图片',exact=True)).to_be_enabled()
    click('保存图片');saved()
    expect(page.get_by_label('进群欢迎语',exact=True)).to_have_value('未保存文案{name}')
    assert page.evaluate('dirty && closing')
    click('管理欢迎图片')
    expect(page.locator('#photoStatus')).to_have_text('当前欢迎图片')
    click('移除图片');confirm(False)
    expect(page.locator('#editor')).to_be_visible()
    click('移除图片');confirm(True);saved()
    expect(page.get_by_label('进群欢迎语',exact=True)).to_have_value('未保存文案{name}')
    click('管理欢迎图片')
    expect(page.locator('#photoStatus')).to_have_text('未设置欢迎图片')
    click('取消')
    page.locator('#basicsForm button[type=submit]').click();saved()
    assert not page.evaluate('dirty || closing')
    back()
    expect(page.locator('#title')).to_have_text('配置中心')
    page.locator('.row[data-go=basics]').click()
    click('新增地址')
    page.get_by_label('USDT地址',exact=True).fill('TJRabPrwbZy45sbavfcjinPJC18kjpRTv8')
    click('保存地址');saved()
    expect(page.get_by_text('TJRabPrwbZy45sbavfcjinPJC18kjpRTv8',exact=True)).to_be_visible()
    page.locator('[data-edit-address]').first.click()
    page.get_by_label('USDT地址',exact=True).fill('TFMsoNbmzTEU7toDB8LvUhicPHhVQN1KWf')
    click('保存地址');saved()
    expect(page.get_by_text('TFMsoNbmzTEU7toDB8LvUhicPHhVQN1KWf',exact=True)).to_be_visible()
    page.locator('[data-delete-address]').first.click();confirm(False)
    expect(page.locator('[data-delete-address]')).to_have_count(1)
    page.locator('[data-delete-address]').first.click();confirm(True);saved()
    expect(page.locator('[data-delete-address]')).to_have_count(0)
    back();page.locator('.row[data-go=ads]').click();click('新增')
    page.get_by_label('标题',exact=True).fill('图片广告')
    page.get_by_label('广告内容',exact=True).fill('图片广告测试')
    page.locator('#ad_file').set_input_files(dict(name='advert.png',mimeType='image/png',buffer=image.getvalue()))
    expect(page.locator('#adPhotoStatus')).to_have_text('图片已选择，保存规则后生效')
    expect(page.locator('#adPhotoPreview')).to_be_visible()
    page.locator('input[name=rule_groups]').first.check()
    click('保存规则');saved()
    expect(page.get_by_text('图片广告',exact=True)).to_be_visible()
    page.locator('.record').filter(has=page.get_by_text('图片广告',exact=True)).first.get_by_role('button',name='编辑',exact=True).click()
    expect(page.locator('#adPhotoPreview')).to_be_visible()
    click('取消');back();page.locator('.row[data-go=replies]').click();click('新增')
    expect(page.get_by_label('关键词',exact=True)).to_have_attribute('placeholder','多个关键词用空格分隔，例如：你好 欢迎 帮助')
    page.get_by_label('关键词',exact=True).fill('你好 欢迎 帮助')
    page.get_by_label('回复内容',exact=True).fill('多关键词回复')
    page.locator('input[name=rule_groups]').first.check()
    click('保存规则');saved()
    expect(page.get_by_text('你好 欢迎 帮助',exact=True)).to_be_visible()
    back();click('用户')
    page.evaluate("document.documentElement.style.cssText='--tg-theme-bg-color:#16232d;--tg-theme-secondary-bg-color:#101820;--tg-theme-text-color:#edf3f7;--tg-theme-hint-color:#91a5b1;--tg-theme-button-color:#4e9be1'")
    page.screenshot(path=str(output/'interactions-users-dark.png'),timeout=10000)
    assert not errors, errors
    browser.close()
    print('App interactions: compact inline tags, row taps, previous-page return, search/scroll restore, Telegram back, independent drafts, cancel/confirm, duplicate-save prevention, image upload/preview/removal passed.')
